name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --configuration Release --no-build
  
    - name: Publish
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj  --configuration Release --no-build --output ./taa-portal/
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: drop
        path: ${{ github.workspace }}/taa-portal/

  release:

       runs-on: ubuntu-latest
       needs: [build]
       
       steps:
       - name: download 
         uses: actions/download-artifact@v3.0.0
         with:
           name: drop
           path: ./taa-portal/
         
       - name: Azure WebApp
         uses: Azure/webapps-deploy@v2
         with:
        # Name of the Azure Web App
          app-name: TeamTigerWebApp
          publish-profile: ${{ secrets.TEAM_TIGER_WEB_APP }}
          package: ./taa-portal/
          
       - name: Azure Login
         uses: Azure/login@v1.4.4
         with:
          creds: ${{ secrets.TEAM_TIGER_SERVICE_PRINCIPLE }}
          
       - name: Set Web App ACR authentication
         uses: Azure/appservice-settings@v1
         with:
          app-name: 'TeamTigerWebApp'
          app-settings-json: ${{ secrets.TEAM_TIGER_APP_SETTINGS }}
          
       
