name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --configuration Release --no-build
  
    - name: Publish
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj  --configuration Release --no-build --output ./taa-portal
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: drop
        path: ${{ github.workspace }}/taa-portal/
        
    - name: Upload a Bicep Template
      uses: actions/upload-artifact@v3.1.0
      with:
        name: bicep
        path: deploy.bicep

  release:
       if: github.ref == 'refs/heads/master'
       runs-on: ubuntu-latest
       needs: build
       
       steps:
       - name: download 
         uses: actions/download-artifact@v3.0.0
         with:
           name: drop
           path: ./taa-portal
         
       - name: Azure WebApp
         uses: Azure/webapps-deploy@v2
         with:
          app-name: TeamTigerWebApp
          publish-profile: ${{ secrets.TEAM_TIGER_WEB_APP }}
          package: ./taa-portal/
          
       - name: Azure Login
         uses: Azure/login@v1.4.4
         with:
          creds: ${{ secrets.TEAM_TIGER_SERVICE_PRINCIPLE }}     
       
       - uses: Azure/get-keyvault-secrets@v1
         with:
          keyvault: "TeamTigerKeyVault"
          secrets: 'GlobalPassword, SimulatedFailureChance'
         id: myGetSecretAction
          
       - name: Set Web App ACR authentication
         uses: Azure/appservice-settings@v1
         with:
          app-name: 'TeamTigerWebApp'
          app-settings-json: '[{ "name": "GlobalPassword", "value": "${{ steps.myGetSecretAction.outputs.GlobalPassword }}", "slotSetting": false }, { "name": "SimulatedFailureChance", "value": "${{ steps.myGetSecretAction.outputs.SimulatedFailureChance }}", "slotSetting": false }]'
         
  release_to_prod:
     if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     needs: build
       
     steps:
        - name: Download Bicep 
          uses: actions/download-artifact@v3.0.0
          with:
           name: bicep
           path: ./bicep/
       
        - name: Azure Login
          uses: Azure/login@v1.4.4
          with:
            creds: ${{ secrets.TEAM_TIGER_SERVICE_PRINCIPLE_PROD }} 
            
        - name: Deploy Azure Resource Manager (ARM) Template
          uses: Azure/arm-deploy@v1.0.8
          with:
           subscriptionId: cfe96ac1-4cd0-40ad-9751-b18802bf8822
           resourceGroupName: DevOpsGitHub-2022-06-16-team-01-prod
           template: ./bicep/deploy.bicep
           deploymentName: production
           parameters:  tenantGuid=ab5eb3d0-6067-40ee-b4c0-a2ce05dbf039 appServicePlanName=TeamTigerPlanProd keyVaultName=TeamTigerKeyVaultProd webAppName=TeamTigerWebAppProd resourceGroupServicePrincipalManagedApplicationObjectId=c771ce99-6491-477f-9eb6-d1c176d43d1c
          
       
